artifact_uri: /Users/skandanganesh/Documents-Skandan/python_programs/LLM Tutorials/b401-master/DataDialogue/mlflow/332956159344973722/d43628331bf34a35b19af7fe520661e1/artifacts
end_time: 1778034308534
entry_point_name: ''
experiment_id: '332956159344973722'
lifecycle_stage: active
run_id: d43628331bf34a35b19af7fe520661e1
run_name: incongruous-cat-788
source_name: ''
source_type: 4
source_version: ''
start_time: 1778034295639
status: 3
tags: []
user_id: skandanganesh
