artifact_uri: /Users/skandanganesh/Documents-Skandan/python_programs/LLM Tutorials/b401-master/DataDialogue/mlflow/332956159344973722/ecee7e826f4c40e68219c0ca1c859600/artifacts
end_time: 1778015237306
entry_point_name: ''
experiment_id: '332956159344973722'
lifecycle_stage: active
run_id: ecee7e826f4c40e68219c0ca1c859600
run_name: ambitious-vole-776
source_name: ''
source_type: 4
source_version: ''
start_time: 1778015237169
status: 4
tags: []
user_id: skandanganesh
