artifact_uri: /Users/skandanganesh/Documents-Skandan/python_programs/LLM Tutorials/b401-master/DataDialogue/mlflow/332956159344973722/bb0b4594ae2845219fc3ce77b561043a/artifacts
end_time: 1778033770580
entry_point_name: ''
experiment_id: '332956159344973722'
lifecycle_stage: active
run_id: bb0b4594ae2845219fc3ce77b561043a
run_name: resilient-swan-448
source_name: ''
source_type: 4
source_version: ''
start_time: 1778033770341
status: 4
tags: []
user_id: skandanganesh
