artifact_uri: /Users/skandanganesh/Documents-Skandan/python_programs/LLM Tutorials/b401-master/DataDialogue/mlflow/332956159344973722/bfddeaf6d46541248d735df96d0ff06c/artifacts
end_time: 1778035366661
entry_point_name: ''
experiment_id: '332956159344973722'
lifecycle_stage: active
run_id: bfddeaf6d46541248d735df96d0ff06c
run_name: rebellious-skunk-850
source_name: ''
source_type: 4
source_version: ''
start_time: 1778035354040
status: 3
tags: []
user_id: skandanganesh
