artifact_uri: /Users/skandanganesh/Documents-Skandan/python_programs/LLM Tutorials/b401-master/DataDialogue/mlflow/332956159344973722/3287fd4b4a9145d38367dfb11d770746/artifacts
end_time: 1778015368603
entry_point_name: ''
experiment_id: '332956159344973722'
lifecycle_stage: active
run_id: 3287fd4b4a9145d38367dfb11d770746
run_name: peaceful-eel-793
source_name: ''
source_type: 4
source_version: ''
start_time: 1778015368445
status: 4
tags: []
user_id: skandanganesh
