artifact_uri: /Users/skandanganesh/Documents-Skandan/python_programs/LLM Tutorials/b401-master/DataDialogue/mlflow/332956159344973722/046834c6ac4a4e64965bdfed03fcf801/artifacts
end_time: 1778014682822
entry_point_name: ''
experiment_id: '332956159344973722'
lifecycle_stage: active
run_id: 046834c6ac4a4e64965bdfed03fcf801
run_name: overjoyed-panda-359
source_name: ''
source_type: 4
source_version: ''
start_time: 1778014682670
status: 4
tags: []
user_id: skandanganesh
