artifact_uri: /Users/skandanganesh/Documents-Skandan/python_programs/LLM Tutorials/b401-master/DataDialogue/mlflow/332956159344973722/785501a70fee42af9b7d0e596cddd913/artifacts
end_time: 1778015393028
entry_point_name: ''
experiment_id: '332956159344973722'
lifecycle_stage: active
run_id: 785501a70fee42af9b7d0e596cddd913
run_name: efficient-rat-938
source_name: ''
source_type: 4
source_version: ''
start_time: 1778015392889
status: 4
tags: []
user_id: skandanganesh
