artifact_location: /Users/skandanganesh/Documents-Skandan/python_programs/LLM Tutorials/b401-master/DataDialogue/mlflow/0
creation_time: 1778011909306
experiment_id: '0'
last_update_time: 1778011909306
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
