artifact_location: /Users/skandanganesh/Documents-Skandan/python_programs/LLM Tutorials/b401-master/DataDialogue/mlflow/332956159344973722
creation_time: 1778011909310
experiment_id: '332956159344973722'
last_update_time: 1778011909310
lifecycle_stage: active
name: DataDialogue
trace_location: null
workspace: default
