artifact_uri: /Users/skandanganesh/Documents-Skandan/python_programs/LLM Tutorials/b401-master/DataDialogue/mlflow/332956159344973722/bb080ea157454cb5bba86ed8236dc75e/artifacts
end_time: 1778033509159
entry_point_name: ''
experiment_id: '332956159344973722'
lifecycle_stage: active
run_id: bb080ea157454cb5bba86ed8236dc75e
run_name: placid-hen-575
source_name: ''
source_type: 4
source_version: ''
start_time: 1778033508985
status: 4
tags: []
user_id: skandanganesh
